### ISSUE TITLE
Add OpenSuse rpm package generation

### ISSUE THREAD

**Issue by tobias-klein** [ezra-project/ezra-project#142]

**Comment by tobias-klein** [comment]
@reyespinosa1996
Could you test the package available in the [latest GitHub build](https://github.com/ezra-project/ezra-project/actions/runs/384860633).

Note that this is for OpenSuse Leap 15.2.

**Comment by reyespinosa1996** [comment]
I do test it. It works fine for me on OpenSuse Leap 15.2.

**Comment by tobias-klein** [comment]
Thanks for the confirmation! Closing this issue now.
