### ISSUE TITLE
Translation update for Ezra Project 0.16.0

### ISSUE THREAD

**Issue by tobias-klein** [ezra-project/ezra-project#149]
The following strings newly added for 0.16.0 need to be translated:

* module-install-cancelled (see #109)
* show-header-navigation (see #135)
* fullscreen (see #134)
* select-all-search-results (see #132)
* all-search-results
* some-search-results

@lemtom Could you submit a pull request for the French and Dutch translation.
@MartinIIOT Could you submit a pull request for the Slovakian translation.
@reyespinosa1996 Could you submit a pull request for the Spanish translation.

I am planning to release 0.16.0 on December 20th.
Thanks for your help!

**Comment by reyespinosa1996** [comment]
I do not have clear enough where is the development branch for 0.16, are you making commits directly to master?

**Comment by tobias-klein** [comment]
There is no separate development branch. master is the base! :)

**Comment by tobias-klein** [comment]
@MartinIIOT
I added some more strings, sorry for the late change. This is the final update - the related issue is implemented now.
Could you send another patch for:
* all-search-results
* some-search-results

Thanks!

**Comment by reyespinosa1996** [comment]
I added a missing string to es translation file at line 179, and translate all the new strings. All the changes are available at es-translation-update. I hope to use this branch for every single change on Spanish translation for now long.

**Comment by tobias-klein** [comment]
@LAfricain Would you have a chance to take care of the French translation this time?

**Comment by reyespinosa1996** [comment]
0.16 is schedule to release today. Is there any issue or is ready to release as scheduled?

**Comment by lemtom** [comment]
I'm not a native speaker of French, so having someone else take a look at my translations could be useful in any case.

**Comment by tobias-klein** [comment]
Excellent! Thanks, @lemtom.
I'll merge later and then initiate the release procedure!
