### ISSUE TITLE
Android tablet support

### ISSUE THREAD

**Issue by tobias-klein** [ezra-project/ezra-project#150]
See the [description of this idea in the user forum](https://forum.ezra-project.net/topic/4/ezra-project-for-tablets-android-ios).

Porting status:
- [x] node-sword-interface build for Android
- [x] Cordova-based application wrapper
- [x] Bundle JS files to further optimize startup performance and enable Cordova integration
- [x] Implement abstract IPC interface to communicate with the backend
- [x] Move all backend functionality to main process (see #158)
- [x] Align SWORD storage directory
- [x] Move from Electron settings store to Node.js based settings store (see #159)
- [x] Implement Android-specific fullscreen toggling
- [x] Android specific performance tweaks
- [x] Ensure that localization works
- [x] Android specific formatting / CSS
- [x] Robustness testing
- [x] Submit app to Google Play Store
- [x] Update websites & wikis with infos about the Android app

**Comment by tobias-klein** [comment]
@romanlnk @pastortonya @pixelious @Bohooslav @hashaway @seven1m @dcampos @mwatts @takelley1 @throughtheblack3 @lindseyesch @jajpater @andrei-a-papou @mabo85 @felenk @muniter @kai5263499 @jhenterprise @PiterPentester @engineervix @ipstone @Seniru @mozmck @alerque @tuomas2

I am reaching out to the star gazers of this repository! Do you have a 10" Android Tablet and can help with some testing?
An early beta version for Ezra Project on Android is available here:
https://play.google.com/store/apps/details?id=de.ezraproject.cordova

Would you mind trying it out and giving me feedback?
These are the things I am interested in:
1) What device do you have? (Exact model)
2) Which Android version?
3) Did you encounter any issues?
4) Any other interesting observations?
5) Can you provide a debug log? You can do that by enabling Development mode on your tablet, attaching it via USB and running the following command before starting up the app (ADB Tools required): `adb logcat | grep NODE`

Looking forward to any feedback.

**Comment by jajpater** [comment]
I had one, but I gave it away. :-(

**Comment by Bohooslav** [comment]
Sadly, I don't have one.
