### ISSUE TITLE
Translation update for Ezra Project 0.17.0

### ISSUE THREAD

**Issue by tobias-klein** [ezra-project/ezra-project#178]
The following strings newly added for 0.17.0 need to be translated:

* module-application-info
* application-info
* sword-module-description
* sword-module-details
* sword-version
* chromium-version
* open-verse-lists-in-new-tab

Note that there are additional Android-specific strings that also need translation, but for this release I am not going to yet enable other languages than English for the Android user interface (because the i18n component is not fully ported yet).
So, the Android-specific strings will then need translation in the next release, I am trying to fix the i18n component until then.

@lemtom Could you submit a pull request for the French and Dutch translation.
@MartinIIOT Could you submit a pull request for the Slovakian translation.
@reyespinosa1996 Could you submit a pull request for the Spanish translation.

I am planning to release 0.17.0 on February 20th. Thanks for your help!

**Comment by tobias-klein** [comment]
@MartinIIOT
@reyespinosa1996
Any chance you guys can submit pull requests until Friday?

**Comment by reyespinosa1996** [comment]
I have some issues at work but I'll try to do it by tomorrow.
-- 
 Enviado con Tutanota, el correo seguro y sin publicidad: 
 https://tutanota.com


16 de febrero de 2021 1:09 p. m. por notifications@github.com:

**Comment by reyespinosa1996** [comment]
Translation to Spanish is ready for revision and approval.

**Comment by tobias-klein** [comment]
Thanks all of you! Excellent work. All translations updated, closing this issue now.
