### ISSUE TITLE
Failure to install certain modules where the module id is not located in the first line of the *.conf file

### ISSUE THREAD

**Issue by tobias-klein** [ezra-project/ezra-project#179]
There is an issue with installing modules where the module id is not located in the first line of the *.conf file. This was observed with the newly available CrossWire module "GerMenge". When attempting to install a module like that the installation assistant simply hangs at the step of module installation and never closes. In the background an error message like this is given by node-sword-interface:

`getModuleFromList: Did not find module GerMenge in modulelist!`

**Comment by DavidHaslam** [comment]
**GerMenge** is one of the recently released modules for which the CONF file now includes _descriptive comment_ lines:
```
## Sword module configuration file

## Required elements
# Module Unique Identifier.
[GerMenge]
...
```

The installer needs to cope with both comment lines and blank lines before the module ID.

**Comment by tobias-klein** [comment]
Yes! I found the root-cause and a bugfix is on its way.

**Comment by DavidHaslam** [comment]
I have also updated the documentation. See [here](https://wiki.crosswire.org/DevTools:conf_Files#Comments_and_blank_lines).
