### ISSUE TITLE
Stuck on startup at "Loading... Loading settings"

### ISSUE THREAD

**Issue by jjvano** [ezra-project/ezra-project#185]
Stuck on app startup at "Loading... Loading settings".  Was just prior working; was entering notes and saving before it closed after a while and will not open, even after tablet restart or cache clearing.

app version 0.17.1
10" tablet (Samsung Tab A: SM-T510)
Android 10

**Comment by tobias-klein** [comment]
Hi @jjvano 
Thanks for reporting this issue! Did it somehow resolve after trying again? Or did you accidentally close this issue?

**Comment by tobias-klein** [comment]
If you still have this issue ...
Can you try to delete the following two files using an app like [ES File Explorer](https://play.google.com/store/apps/details?id=com.filemanager.lnapp):
* `/sdcard/Android/data/de.ezraproject.cordova/html-cache.json`
* `/sdcard/Android/data/de.ezraproject.cordova/config.json`

This will keep the database intact, but reset the settings & internal cache.

**Comment by jjvano** [comment]
Sorry, about reporting it.  I finally uninstalled it but it allowed me to save the downloaded content.  I reinstalled and now it works and I still have all my notes, bibles, and dictionaries.  Thank you for a great app!  I've been using it on the computer and am enjoying the availability on the tablet.

**Comment by tobias-klein** [comment]
I'm glad you found a way to make it work again! Technically this is still a bug and I need to check what could be the root-cause.

If you are using Ezra Project on multiple devices it may be useful to synchronize the database across multiple devices and have it in sync whenever you switch between your devices!

I just wrote a [howto on how to accomplish that using a service like Dropbox (or Nextcloud)](https://ezra-project.net/howto/synchronize_database_with_multiple_devices).

Let me know if that works for you!

**Comment by tobias-klein** [comment]
Oh, and would you mind leaving a review in the Play Store? :)
