### ISSUE TITLE
Tab options can't be seen when a lot of tabs are open

### ISSUE THREAD

**Issue by zhuiks** [ezra-project/ezra-project#200]
When a lot of tabs are open and they take more then one full row the tab options menu (buttons) can not be seen:

![Screenshot from 2021-03-22 14-57-44](https://user-images.githubusercontent.com/3584119/112050596-09d2f780-8b1f-11eb-86aa-15d9c36aa1b8.png)

**Comment by tobias-klein** [comment]
This is only a problem in the current development version. I believe this works in all released versions.

**Comment by tobias-klein** [comment]
It now looks like this.

![image](https://user-images.githubusercontent.com/17739895/112107161-e3f53380-8bae-11eb-9e5d-012d32155b40.png)

Before it looked like this:

![image](https://user-images.githubusercontent.com/17739895/112107302-1141e180-8baf-11eb-9b88-72e058477a69.png)

So now the background of the tab bar is expanding all the way to the right.

Generally I would prefer the previous look ... I'll check whether this can be achieved with CSS adjustments.

**Comment by tobias-klein** [comment]
I changed some CSS for .ui-tabs-nav and now it looks as before!

Thanks for the fullscreen icon handling! :)
