### ISSUE TITLE
New app logo

### ISSUE THREAD

**Issue by zhuiks** [ezra-project/ezra-project#214]
Maybe the logo should be a little bit more interesting.
How about something like this:

------
Update: removed first attempt to the comment below so not to spoil the first impressions

Update2: The latest version:
![logo8](https://user-images.githubusercontent.com/3584119/114562857-80ea4000-9c34-11eb-938f-902da1e6ca09.png)

**Comment by zhuiks** [comment]
@alerque What do you think?

**Comment by alerque** [comment]
Let me get out my microscope...

I'd say this is an improvement that leaves room for improvement. I'm not much of a designer type myself so take my comments with the proverbial grain. Perhaps the thing that bothered me most was how long it took me to figure out what the blobs were in front of the scroll. Obvious once you see it, but it took me a while. Maybe it was that the head is disembodied, maybe the person could use some treatment such as maybe an outline with a lighter fill.

Either way if your focus is a little blurry it's hard for the scroll not to look like the dude 's got his hands in the air.

Sorry if that's too critical. I actually like it, but at the same time it could use some tweaking. But I'm not qualified to do the tweaking, so perhaps seek the opinion of somebody with the right skill set.

**Comment by zhuiks** [comment]
Thank you for your critical review! In my case it's inspiring :smile: 

> Let me get out my microscope...

Hmm, I didn't realize it would be so small on the phones...

Here is another more minimalistic approach: 
![Logo 3](https://user-images.githubusercontent.com/3584119/114056589-70fae680-9857-11eb-84ce-0ef5b8894e3a.png) 
![Logo 3(1)](https://user-images.githubusercontent.com/3584119/114057650-59702d80-9858-11eb-97c2-d98fc4f1818f.png)
![Logo 3](https://user-images.githubusercontent.com/3584119/114057623-537a4c80-9858-11eb-9a62-e36c99584f81.png)

**Comment by alerque** [comment]
I wasn't an a phone, I was on a massive desktop monitor spread ;-)

First impressions of the more minimalist approach: Fantastic! Of course I've lost the benefit of truly first impressions, this time I was expecting a person reading a scroll, but the simplicity still gets the idea across with getting quite so muddled in the process.

For larger sizes (and resolutions) where we get more to work with (such as mobile app icons) perhaps more detail would be in order, but I like the way this scaled down.

The scrolls at the side could perhaps use something solid in them, at least going down if not protruding anywhere. They look a bit like waves...

**Comment by tobias-klein** [comment]
I like the second proposal much better than the first one! I also prefer simplicity (good logos are usually simple)
How about turning the scroll type thing into an actual book/bible?

I am going to request feedback on this from the "star gazers" of this repo:
@jameschensmith @BryanHo10 @Stratus3D @jjvano @1kingofwonders @eevargas @qauche @romanlnk @pastortonya @pixelious @Bohooslav @hashaway @seven1m @dcampos @mwatts @takelley1 @throughtheblack3 @lindseyesch @jajpater @andrei-a-papou @mabo85 @felenk @muniter @kai5263499 @jhenterprise @PiterPentester @engineervix @ipstone @Seniru @mozmck @alerque @DavidHaslam @tuomas2

**Comment by zhuiks** [comment]
Mod from the comment:
> The scrolls at the side could perhaps use something solid in them, at least going down if not protruding anywhere. They look a bit like waves...

![Logo 4](https://user-images.githubusercontent.com/3584119/114091146-eaa5cb00-987d-11eb-9b5d-ea2061fe4fcb.png) ![Logo 4(1)](https://user-images.githubusercontent.com/3584119/114091280-17f27900-987e-11eb-8a99-2ea2a2f52f73.png)

**Comment by Stratus3D** [comment]
@tobias-klein , @zhuiks updated graphic in his latest comment looks good! The circle seems to be a little lacking in detail compared to the scroll, but don't think it's a problem.

**Comment by Stratus3D** [comment]
If you wanted to you could a a stick man style neck and arms below the head and above the scroll.

**Comment by zhuiks** [comment]
The version with a book instead of a scroll is present in "book reader" icons, i.e [Font Awesome](https://fontawesome.com/icons/book-reader?style=solid):

![book-reader](https://user-images.githubusercontent.com/3584119/114092207-3b69f380-987f-11eb-9082-c057877ef043.png)

**Comment by zhuiks** [comment]
Initial idea:
![Logo64](https://user-images.githubusercontent.com/3584119/114092694-cc40cf00-987f-11eb-8de8-a454d7bc69d1.png)

**Comment by alerque** [comment]
I think the scroll tweak did help.

I'm not a fan of the book variant. Maybe it's because I work as a typesetter and sort through books all day, but the motif seems overused. And after all Ezra didn't have bound leaf books.

**Comment by hashaway** [comment]
> Initial idea:
> ![Logo64](https://user-images.githubusercontent.com/3584119/114092694-cc40cf00-987f-11eb-8de8-a454d7bc69d1.png)

I like this. The image prompted me to take a second look. If the logo can grab the viewer's attention for longer than a mere quick glance, then it serves to compliment an App that is created with user retention in mind :o)

**Comment by hashaway** [comment]
@zhuiks Maybe it would look a bit better if we made the black horizontal outline of the scroll on either side of the head a little lighter. See sample below.

Sample:
![114092694-cc40cf00-987f-11eb-8de8-a454d7bc69d1-edit](https://user-images.githubusercontent.com/34164202/114177620-e8ef0c80-993c-11eb-89f0-381f6c1bdd81.png)

**Comment by zhuiks** [comment]
@hashaway Thank you for your input, I appreciate it

I think your sample didn't got into the answer. Can you please try it again. I'm interested to see what do you mean.
Here is svg version of that icon:
[Logo 1.zip](https://github.com/ezra-project/ezra-project/files/6286477/Logo.1.zip)


> Maybe it would look a bit better if we made the black horizontal outline of the scroll on either side of the head a little lighter. See sample below.
> 
> Sample:
> ![114092694-cc40cf00-987f-11eb-8de8-a454d7bc69d1-edit](https://user-images.githubusercontent.com/34164202/114177620-e8ef0c80-993c-11eb-89f0-381f6c1bdd81.png)

**Comment by zhuiks** [comment]
> I'm not a fan of the book variant. Maybe it's because I work as a typesetter and sort through books all day, but the motif seems overused. And after all Ezra didn't have bound leaf books.

@alerque I'm agreeing with that. I think the logo should somehow should communicate  the slogan (is that a slogan?) idea:
> "For Ezra had set his heart to study the Law of the LORD,
and to do it and to teach his statutes and rules in Israel." Ezra 7:10 

I'm personally leaning towards "waves" form of the scroll. It looks more authentic. Although I agree those should be tuned to look less like waves. I'll play with it.
The latest version with circled scroll ends is too "iconish". It misses details.

I was thinking that adding text lines on the scroll would not be correct as most of the scrolls including OT scrolls were one-sided at that time.
I might add some cracks on the scroll to add a little bit of "ancient legacy".

It would be nice to add some details to the head without compromising the basic shape. 
I'm thinking adding text/letters background (Hebrew transcription?) so head would stand out.
So I'll be back...

And a little disclaimer: I'm not a pro designer...

**Comment by zhuiks** [comment]
I think that's all I can do...

![Logo 7](https://user-images.githubusercontent.com/3584119/114246617-ad623b80-9958-11eb-8f7c-c11c891c6b5f.png) ![Logo 5(1)](https://user-images.githubusercontent.com/3584119/114251632-54e66a80-9967-11eb-9af9-e7026a3d1f6d.png)


I'm not sure about Hebrew. Just copy-pasted it from Genesis. My graphic editor might goofed up the order of the letters/words...

**Comment by hashaway** [comment]
> @hashaway Thank you for your input, I appreciate it
> 
> I think your sample didn't got into the answer. Can you please try it again. I'm interested to see what do you mean.
> Here is svg version of that icon:
> [Logo 1.zip](https://github.com/ezra-project/ezra-project/files/6286477/Logo.1.zip)
> 
> > Maybe it would look a bit better if we made the black horizontal outline of the scroll on either side of the head a little lighter. See sample below.
> > Sample:
> > ![114092694-cc40cf00-987f-11eb-8de8-a454d7bc69d1-edit](https://user-images.githubusercontent.com/34164202/114177620-e8ef0c80-993c-11eb-89f0-381f6c1bdd81.png)

I lightened the horizontal line slightly in the sample because to me it appeared too stark against the head of the person reading the scroll.

Here is a visual of what I mean:

![Logo-1-edit](https://user-images.githubusercontent.com/34164202/114259577-3320ce00-99cf-11eb-9900-936fff0ed144.png)

I am not a designer, but I like your image :o)

**Comment by hashaway** [comment]
@tobias-klein Will the new domain name include the name Ezra, or are you going to do a complete rebrand?

These are not exactly App Logos but if you keep the name Ezra and verse 7:10 as the slogan, then maybe one of these images will be useful somewhere in the site.

![Ezra-No-11](https://user-images.githubusercontent.com/34164202/114272175-5d957a00-9a15-11eb-8f90-268259fa849e.png)
![Ezra-No-10](https://user-images.githubusercontent.com/34164202/114272181-60906a80-9a15-11eb-8058-d3a130b97548.png)
![Ezra-No-9](https://user-images.githubusercontent.com/34164202/114272184-61290100-9a15-11eb-935d-e3894b8e78ee.png)

**Comment by hashaway** [comment]
@zhuiks Here are some ideas for filling in the empty space in the scroll.

![insert-1](https://user-images.githubusercontent.com/34164202/114275539-35147c80-9a23-11eb-9979-178af1931eb6.png)


![insert-2](https://user-images.githubusercontent.com/34164202/114275535-32b22280-9a23-11eb-962b-1e37cb2d2190.png)

**Comment by Bohooslav** [comment]
I wonder what if they would kill Jesus with rifle. Would you make rifle your logo?

**Comment by zhuiks** [comment]
@hashaway Thank you for your ideas!

The cross is central for Christianity therefor the symbol.

If we choose to bring the cross into the logo, I would put it in the background in place of the text. That would keep design logic in tact. But as for now I personally prefer to keep the main idea of the logo very simple: "person with a scroll". That way there is no additional informational overload for a user in our current overloaded with information world. Extra details might come later after using the app and stearing on the logo for some time: Ezra/user reading old scroll, hebrew scroll, Bible hebrew scroll, Bible with interlinear hebrew/greek text (coming up in 0.19), Christ in all scriptures

I like the general idea behind your illustration for Ezra 7:10 and it's composition. Although it's a bit "clip-artish". Maybe font can be more simple. Maybe take only first half of the verse and start at the bottom left position. Maybe at the bottom could be just the centered reference right side up. That way an extra space would help to understand from where to start reading.

**Comment by hashaway** [comment]
> @hashaway Thank you for your ideas!
> 
> The cross is central for Christianity therefor the symbol.
> 
> If we choose to bring the cross into the logo, I would put it in the background in place of the text. That would keep design logic in tact. But as for now I personally prefer to keep the main idea of the logo very simple: "person with a scroll". That way there is no additional informational overload for a user in our current overloaded with information world. Extra details might come later after using the app and stearing on the logo for some time: Ezra/user reading old scroll, hebrew scroll, Bible hebrew scroll, Bible with interlinear hebrew/greek text (coming up in 0.19), Christ in all scriptures
> 
> I like the general idea behind your illustration for Ezra 7:10 and it's composition. Although it's a bit "clip-artish". Maybe font can be more simple. Maybe take only first half of the verse and start at the bottom left position. Maybe at the bottom could be just the centered reference right side up. That way an extra space would help to understand from where to start reading.

@zhuiks  Thank you for your constructive feedback :o)

**Comment by hashaway** [comment]
> I wonder what if they would kill Jesus with rifle. Would you make rifle your logo?

@Bohooslav Your comment made me think for a moment :o)

We would definitely not make a rifle the Logo, if that were to have been used as the method to execute Jesus. The Lord would not have said "take up your rifle and follow me" (because that would be contrary to His nature). Instead he said, "...take up your cross and follow me...". The attitude of heart pertaining to the cross is conducive to a Life of total surrender, and relevant to who the Christ Is. Without the power of the cross in the life of a believer, he/she would be spiritually bankrupt. We are to take up our cross daily, and follow our Risen King.

**Comment by tobias-klein** [comment]
Let's try to keep the logo as simple as possible. I would actually suggest to stick with this version, I really like the simplicity of it. 

> ![Logo 4](https://user-images.githubusercontent.com/3584119/114091146-eaa5cb00-987d-11eb-9b5d-ea2061fe4fcb.png) ![Logo 4(1)](https://user-images.githubusercontent.com/3584119/114091280-17f27900-987e-11eb-8a99-2ea2a2f52f73.png)

Putting additional things in the background or on the scroll is not necessary in my view and makes it harder to keep it nice looking when you scale the logo to smaller versions or even a 16 by 16px icon. Also, I suggest keeping the head as a simple circle (instead of the later posted oval version).

How about using the rolled edges of the later version, though?
![image](https://user-images.githubusercontent.com/17739895/114300236-7fe3d200-9abf-11eb-9f0c-d5d13ad3dd8b.png)

I think those actually make it look nicer.

The "cracked" look in the latest version is not necessary I think. It again takes away from the simplicity.

**Comment by zhuiks** [comment]
> Let's try to keep the logo as simple as possible. I would actually suggest to stick with this version, I really like the simplicity of it.

@tobias-klein Thanks for your final judgement
How about head shape variations:
![Logo 8(4)](https://user-images.githubusercontent.com/3584119/114407818-6baade00-9b6e-11eb-8830-a661e10ef865.png) ![Logo 8(4)-64](https://user-images.githubusercontent.com/3584119/114408489-13c0a700-9b6f-11eb-988d-f66bfa201bfb.png)


![Logo 8(2)](https://user-images.githubusercontent.com/3584119/114407833-706f9200-9b6e-11eb-91bb-8c8016da8777.png) ![Logo 8(2)-64](https://user-images.githubusercontent.com/3584119/114408480-115e4d00-9b6f-11eb-9260-bdc27eca86c1.png)



![Logo 8(1)](https://user-images.githubusercontent.com/3584119/114407838-736a8280-9b6e-11eb-83cc-18244d355737.png) ![Logo 8(1)-64](https://user-images.githubusercontent.com/3584119/114408457-0b686c00-9b6f-11eb-8a76-d0ffe0c72eb3.png)

I would choose between the first ("realistic"-head) and the third (circle-head)

**Comment by alerque** [comment]
Personally I like the middle variant, ogg shaped but not too fancy. The more shaped one looks like my current beard but somehow it doesn't fit. The round one lends itself too much to other possible non-person objects and still makes me do a double take to figure out what's what. The egg strikes a balance somehow making my brain comfortable with the neckless head while not being too distracting.

**Comment by zhuiks** [comment]
@alerque Thanks. After have been staring  at it I agree with you.

Here is the winner:
![logo8](https://user-images.githubusercontent.com/3584119/114563647-34ebcb00-9c35-11eb-906d-693297b046e0.png)

It's not perfect, but better than what we have now.

Thanks everybody for participating in this discussion.
