### ISSUE TITLE
Translation update for 0.18.0

### ISSUE THREAD

**Issue by tobias-klein** [ezra-project/ezra-project#220]
The following strings updated or newly added for 0.18.0 need to be translated:

* show-parallel-translations
* compare
* context
* fullscreen
* exit-fullscreen
* text-size
* text-size-decrease
* text-size-reset
* text-size-increase
* repo-selection-info-text
* select-dictionaries-to-be-removed
* module-application-info
* application-info
* sword-module-description
* sword-module-details
* application-version
* git-commit
* chromium-version
* database-path
* config-file-path
* new-release-available-body
* developers
* translators
* versions-and-paths
* change-tags
* most-frequently-used
* less-frequently-used
* module-search-cancelled
* show-book-chapter-navigation
* show-notes-tags-indicators
* keep-screen-on
* adjust-font-size-tags-notes
* new-note-hint
* welcome-to-ezra-bible-app
* storage-justification
* enable-storage-access
* storage-permission-denied
* permanent-permission-decision-part1
* permanent-permission-decision-part2

@lemtom Could you submit a pull request for the French and Dutch translation.
@MartinIIOT Could you submit a pull request for the Slovakian translation.
@reyespinosa1996 Could you submit a pull request for the Spanish translation.

I am planning to release 0.18.0 on April 24th/25th. Thanks for your help!

**Comment by tobias-klein** [comment]
@reyespinosa1996 
@lemtom 
Friendly reminder :)

**Comment by reyespinosa1996** [comment]
Oh God,  I was just too busy and I didn't check Github.

**Comment by reyespinosa1996** [comment]
@tobias-klein let me ask you something. Ezra in Spanish means Esdras wish is the Spanish way to spell it. In order to keep the brand I propose not to translate into spanish the full application name and leave it like Ezra Bible App. I just see you sugest that changes have to be made to some strings but I strongly advise to keep the brand with the English style.

**Comment by tobias-klein** [comment]
Yes, I would suggest to keep the product name **Ezra Bible App**

**Comment by reyespinosa1996** [comment]
We are in the same page here 👌
