### ISSUE TITLE
Adjustable font-size for bible text

### ISSUE THREAD

**Issue by tobias-klein** [ezra-project/ezra-project#42]

**Comment by tobias-klein** [comment]
The icons could look like this:

![](https://camo.githubusercontent.com/761556584b7476d9e415ba0865dfdd7a44f5b5f1/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f343332303539332f313134353635312f39623135393938632d316532362d313165332d386233342d6433393265303064313837662e504e47)

**Comment by zhuiks** [comment]
Do you think this could be done directly on menu panel vs inside display option dialog?
If so then it should be a separate component, is that correct?

**Comment by tobias-klein** [comment]
I think it may be good if those plus/minus buttons for the font size would be available in the menu directly. And yes ... it could be a very simple new JS component ... probably just with 2-3 methods (init, enlarge, reduce). Alternatively those methods could simply be integrated in the AppController class.

Would you like to take it on?

**Comment by tobias-klein** [comment]
Oh ... And in any case the font size should be applied globally (for all tabs) and also persisted in the configuration.
