### ISSUE TITLE
Show verse notes in hint/popup when hovering over "N" and open editor when clicking on it

### ISSUE THREAD

**Issue by tobias-klein** [ezra-project/ezra-project#76]
In case the verse notes column is not shown permanently it would be useful to have a popup show up when hovering over the "N" on the left side of a verse. The mouseover option obviously only works on the desktop, but the  click functionality could be working both on the desktop and on Android.

Then, when clicking on it, the note could be opened in an editor.

**Comment by zhuiks** [comment]
@tobias-klein What do you think about this approach (it's not exactly a popup):

![Screenshot from 2021-03-24 23-30-15](https://user-images.githubusercontent.com/3584119/112419265-1ad76080-8cf9-11eb-9500-0a7b7abeb57f.png)

**Comment by tobias-klein** [comment]
I like it! Using this approach the notes info does not get in your way and nicely integrates with the text. I'd be fine to keep it like this.

Observations:
1) I noticed that the editor is enabled after clicking the notes indicator a second time. I would suggest to instead use the second click to hide the box again, since you can already click on the note box itself to enable editing. Otherwise the hiding/closing must be handled otherwise. I think clicking on the notes indicator to toggle the box would be most intuitive.
2) When editing the notes text and then clicking the cancel button, the notes box is closed and hidden. This is not expected behavior. In this case the regular box content needs to be rendered again (this is implemented for the existing notes editing based on the notes column).
3) When the option "limit notes size" is enabled, the scrollbar of the notes editor is not rendered (compare with the regular notes editing).
4) I think the width of the notes box should match the width that is used for the regular notes column.
5) For some reason the header color in the rendered notes text is different from the color used when the regular notes column is active. (I observed this in the light color theme, did not test with night mode)
6) The title of the notes indicator shows the raw markdown text. In general the title attribute cannot deal with markup. The only way to have formatting there would be to implement a custom mouseover title handling. An alternative would be to render the notes text into plaintext - but there we also have to research whether this is possible without major effort.

**Comment by zhuiks** [comment]
Thanks for checking. 
With 1 and 2 implemented it's much nicer behaviour.

I did some style refactoring with tags and notes and text width. Now it's all should be consistent (4) and simpler.

I'm still working on 3

**Comment by tobias-klein** [comment]
I remember struggling with the note scroll bar when I implemented the limit notes size feature ... maybe I can support a bit later/tomorrow.

**Comment by tobias-klein** [comment]
There is a change in formatting that I would suggest to revert. When tags are hidden or not display in the column mode it makes sense to give the notes column more space horizontally (that was the previous implementation). I think in that case the space was divided 50/50 between the verse text and the notes column. In case the tags are shown the second half is then split between tags and notes.

## Current formatting (latest state on the feature branch)
![Bildschirmfoto 2021-03-26 um 15 31 33](https://user-images.githubusercontent.com/17739895/112647053-68161800-8e48-11eb-9639-2928d38edae2.png)

![Bildschirmfoto 2021-03-26 um 15 35 19](https://user-images.githubusercontent.com/17739895/112647514-e672ba00-8e48-11eb-8825-4493b686040d.png)

## Previous formatting (0.17.0)

![Bildschirmfoto 2021-03-26 um 15 30 08](https://user-images.githubusercontent.com/17739895/112646849-31400200-8e48-11eb-8dbe-ab80bc7a4d23.png)

![Bildschirmfoto 2021-03-26 um 15 40 01](https://user-images.githubusercontent.com/17739895/112648198-8defec80-8e49-11eb-9479-201d03aef44e.png)
